# Generated by Django 3.1.7 on 2021-03-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charges',
            name='vehicle_type',
            field=models.IntegerField(choices=[(0, 'TWO_WHEELER'), (1, 'THREE_WHEELER'), (2, 'FOUR_WHEELER')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'PARKING_LOT'), (1, 'CUSTOMER')], default=1),
        ),
    ]
