# Generated by Django 3.1.7 on 2021-03-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
