# Generated by Django 3.1.7 on 2021-03-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0002_auto_20210327_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[('0', 'PARKING_LOT'), ('1', 'CUSTOMER')], default='1'),
        ),
    ]
