# Generated by Django 3.1.7 on 2021-03-27 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0002_auto_20210327_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='charges',
            name='charges_per_hour',
            field=models.IntegerField(default=10, verbose_name=django.core.validators.MinValueValidator(0)),
            preserve_default=False,
        ),
    ]
