# Generated by Django 3.1.7 on 2021-03-27 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0003_charges_charges_per_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charges',
            name='charges_per_hour',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
