# Generated by Django 3.1.7 on 2021-03-27 08:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0004_auto_20210327_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now=True)),
                ('exit_time', models.DateTimeField(null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('parking_lot_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parkinglot.parkinglot')),
            ],
        ),
        migrations.RenameField(
            model_name='charges',
            old_name='parkingLotRef',
            new_name='parking_lot_ref',
        ),
        migrations.RemoveField(
            model_name='charges',
            name='vehicle_type',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.IntegerField(choices=[(0, 'COD')], default=0)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('parking_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parkinglot.parking')),
            ],
        ),
    ]
