# Generated by Django 3.1.7 on 2021-03-27 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0006_auto_20210327_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkinglot',
            old_name='lat',
            new_name='latCord',
        ),
    ]
