# Generated by Django 3.1.7 on 2021-03-27 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0007_auto_20210327_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='longCord',
            field=models.DecimalField(decimal_places=15, default=1, max_digits=18, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
            preserve_default=False,
        ),
    ]
