# Generated by Django 3.1.7 on 2021-03-27 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0009_auto_20210327_1348'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='charges',
            unique_together={('parking_lot_ref', 'vehicle_type')},
        ),
    ]
