# Generated by Django 3.1.7 on 2021-03-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0010_auto_20210327_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charges',
            name='vehicle_type',
            field=models.IntegerField(choices=[(0, 'TWO_WHEELER'), (1, 'THREE_WHEELER'), (2, 'FOUR_WHEELER')]),
        ),
    ]
